export const LIVROS_BIBLIA = [
  // Antigo Testamento
  { nome: 'Gênesis', abreviacao: 'Gn', testamento: 'AT' as const, numCapitulos: 50 },
  { nome: 'Êxodo', abreviacao: 'Ex', testamento: 'AT' as const, numCapitulos: 40 },
  { nome: 'Levítico', abreviacao: 'Lv', testamento: 'AT' as const, numCapitulos: 27 },
  { nome: 'Números', abreviacao: 'Nm', testamento: 'AT' as const, numCapitulos: 36 },
  { nome: 'Deuteronômio', abreviacao: 'Dt', testamento: 'AT' as const, numCapitulos: 34 },
  { nome: 'Josué', abreviacao: 'Js', testamento: 'AT' as const, numCapitulos: 24 },
  { nome: 'Juízes', abreviacao: 'Jz', testamento: 'AT' as const, numCapitulos: 21 },
  { nome: 'Rute', abreviacao: 'Rt', testamento: 'AT' as const, numCapitulos: 4 },
  { nome: '1 Samuel', abreviacao: '1Sm', testamento: 'AT' as const, numCapitulos: 31 },
  { nome: '2 Samuel', abreviacao: '2Sm', testamento: 'AT' as const, numCapitulos: 24 },
  { nome: '1 Reis', abreviacao: '1Rs', testamento: 'AT' as const, numCapitulos: 22 },
  { nome: '2 Reis', abreviacao: '2Rs', testamento: 'AT' as const, numCapitulos: 25 },
  { nome: '1 Crônicas', abreviacao: '1Cr', testamento: 'AT' as const, numCapitulos: 29 },
  { nome: '2 Crônicas', abreviacao: '2Cr', testamento: 'AT' as const, numCapitulos: 36 },
  { nome: 'Esdras', abreviacao: 'Ed', testamento: 'AT' as const, numCapitulos: 10 },
  { nome: 'Neemias', abreviacao: 'Ne', testamento: 'AT' as const, numCapitulos: 13 },
  { nome: 'Ester', abreviacao: 'Et', testamento: 'AT' as const, numCapitulos: 10 },
  { nome: 'Jó', abreviacao: 'Jó', testamento: 'AT' as const, numCapitulos: 42 },
  { nome: 'Salmos', abreviacao: 'Sl', testamento: 'AT' as const, numCapitulos: 150 },
  { nome: 'Provérbios', abreviacao: 'Pv', testamento: 'AT' as const, numCapitulos: 31 },
  { nome: 'Eclesiastes', abreviacao: 'Ec', testamento: 'AT' as const, numCapitulos: 12 },
  { nome: 'Cântico dos Cânticos', abreviacao: 'Ct', testamento: 'AT' as const, numCapitulos: 8 },
  { nome: 'Isaías', abreviacao: 'Is', testamento: 'AT' as const, numCapitulos: 66 },
  { nome: 'Jeremias', abreviacao: 'Jr', testamento: 'AT' as const, numCapitulos: 52 },
  { nome: 'Lamentações', abreviacao: 'Lm', testamento: 'AT' as const, numCapitulos: 5 },
  { nome: 'Ezequiel', abreviacao: 'Ez', testamento: 'AT' as const, numCapitulos: 48 },
  { nome: 'Daniel', abreviacao: 'Dn', testamento: 'AT' as const, numCapitulos: 12 },
  { nome: 'Oséias', abreviacao: 'Os', testamento: 'AT' as const, numCapitulos: 14 },
  { nome: 'Joel', abreviacao: 'Jl', testamento: 'AT' as const, numCapitulos: 3 },
  { nome: 'Amós', abreviacao: 'Am', testamento: 'AT' as const, numCapitulos: 9 },
  { nome: 'Obadias', abreviacao: 'Ob', testamento: 'AT' as const, numCapitulos: 1 },
  { nome: 'Jonas', abreviacao: 'Jn', testamento: 'AT' as const, numCapitulos: 4 },
  { nome: 'Miqueias', abreviacao: 'Mq', testamento: 'AT' as const, numCapitulos: 7 },
  { nome: 'Naum', abreviacao: 'Na', testamento: 'AT' as const, numCapitulos: 3 },
  { nome: 'Habacuque', abreviacao: 'Hc', testamento: 'AT' as const, numCapitulos: 3 },
  { nome: 'Sofonias', abreviacao: 'Sf', testamento: 'AT' as const, numCapitulos: 3 },
  { nome: 'Ageu', abreviacao: 'Ag', testamento: 'AT' as const, numCapitulos: 2 },
  { nome: 'Zacarias', abreviacao: 'Zc', testamento: 'AT' as const, numCapitulos: 14 },
  { nome: 'Malaquias', abreviacao: 'Ml', testamento: 'AT' as const, numCapitulos: 4 },

  // Novo Testamento
  { nome: 'Mateus', abreviacao: 'Mt', testamento: 'NT' as const, numCapitulos: 28 },
  { nome: 'Marcos', abreviacao: 'Mc', testamento: 'NT' as const, numCapitulos: 16 },
  { nome: 'Lucas', abreviacao: 'Lc', testamento: 'NT' as const, numCapitulos: 24 },
  { nome: 'João', abreviacao: 'Jo', testamento: 'NT' as const, numCapitulos: 21 },
  { nome: 'Atos', abreviacao: 'At', testamento: 'NT' as const, numCapitulos: 28 },
  { nome: 'Romanos', abreviacao: 'Rm', testamento: 'NT' as const, numCapitulos: 16 },
  { nome: '1 Coríntios', abreviacao: '1Co', testamento: 'NT' as const, numCapitulos: 16 },
  { nome: '2 Coríntios', abreviacao: '2Co', testamento: 'NT' as const, numCapitulos: 13 },
  { nome: 'Gálatas', abreviacao: 'Gl', testamento: 'NT' as const, numCapitulos: 6 },
  { nome: 'Efésios', abreviacao: 'Ef', testamento: 'NT' as const, numCapitulos: 6 },
  { nome: 'Filipenses', abreviacao: 'Fp', testamento: 'NT' as const, numCapitulos: 4 },
  { nome: 'Colossenses', abreviacao: 'Cl', testamento: 'NT' as const, numCapitulos: 4 },
  { nome: '1 Tessalonicenses', abreviacao: '1Ts', testamento: 'NT' as const, numCapitulos: 5 },
  { nome: '2 Tessalonicenses', abreviacao: '2Ts', testamento: 'NT' as const, numCapitulos: 3 },
  { nome: '1 Timóteo', abreviacao: '1Tm', testamento: 'NT' as const, numCapitulos: 6 },
  { nome: '2 Timóteo', abreviacao: '2Tm', testamento: 'NT' as const, numCapitulos: 4 },
  { nome: 'Tito', abreviacao: 'Tt', testamento: 'NT' as const, numCapitulos: 3 },
  { nome: 'Filemom', abreviacao: 'Fm', testamento: 'NT' as const, numCapitulos: 1 },
  { nome: 'Hebreus', abreviacao: 'Hb', testamento: 'NT' as const, numCapitulos: 13 },
  { nome: 'Tiago', abreviacao: 'Tg', testamento: 'NT' as const, numCapitulos: 5 },
  { nome: '1 Pedro', abreviacao: '1Pd', testamento: 'NT' as const, numCapitulos: 5 },
  { nome: '2 Pedro', abreviacao: '2Pd', testamento: 'NT' as const, numCapitulos: 3 },
  { nome: '1 João', abreviacao: '1Jo', testamento: 'NT' as const, numCapitulos: 5 },
  { nome: '2 João', abreviacao: '2Jo', testamento: 'NT' as const, numCapitulos: 1 },
  { nome: '3 João', abreviacao: '3Jo', testamento: 'NT' as const, numCapitulos: 1 },
  { nome: 'Judas', abreviacao: 'Jd', testamento: 'NT' as const, numCapitulos: 1 },
  { nome: 'Apocalipse', abreviacao: 'Ap', testamento: 'NT' as const, numCapitulos: 22 },
];

export const TIPOS_ESTUDO = [
  { id: 'narrativa', nome: 'Pregação Narrativa', descricao: 'Foca na história e sequência dos eventos' },
  { id: 'expositiva', nome: 'Pregação Expositiva', descricao: 'Explica detalhadamente versículo por versículo' },
  { id: 'tematica', nome: 'Pregação Temática', descricao: 'Desenvolve um tema central com múltiplos textos' },
  { id: 'textual', nome: 'Pregação Textual', descricao: 'Foca em palavras-chave e sua profundidade' },
  { id: 'devocional', nome: 'Devocional', descricao: 'Reflexão pessoal e aplicação espiritual' },
  { id: 'biblico', nome: 'Estudo Bíblico', descricao: 'Análise contextual e teológica aprofundada' },
];

export const VERSOES_BIBLIA = [
  { id: 'arc', nome: 'Almeida Revista e Corrigida', abreviacao: 'ARC' },
  { id: 'ara', nome: 'Almeida Revista e Atualizada', abreviacao: 'ARA' },
  { id: 'nvi', nome: 'Nova Versão Internacional', abreviacao: 'NVI' },
  { id: 'acf', nome: 'Almeida Corrigida Fiel', abreviacao: 'ACF' },
  { id: 'ntlh', nome: 'Nova Tradução na Linguagem de Hoje', abreviacao: 'NTLH' },
];
